### ISSUE TITLE
Nested every (for) loop issue

### ISSUE THREAD

**Issue by GinoCarlosMiguel** [amyr11/SimplestPlus#13]
- When I try to nest an every loop inside another every loop, it gives me a SemanticError: 'variable' is already declared.
![image](https://github.com/amyr11/SimplestPlus/assets/89961038/e453512c-a8f3-469f-a794-8120e88d9d5a)

**Comment by amyr11** [comment]
Fixed in https://github.com/amyr11/SimplestPlus/commit/0877370937bde3798a2b0f072f20f254f4a67b7f
